/**
 * Phone-prefix sync script.
 *
 * Phone prefixes are static reference data (countries change ~never), so
 * shipping them as a frontend constant beats a per-render API roundtrip.
 * This script is the bridge: backend remains the source of truth, but the
 * generated `src/domain/data/phonePrefixes.ts` is what the app reads.
 *
 * Run after the backend list changes:
 *
 *     pnpm sync:phone-prefixes
 *
 * …and commit the diff.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { z } from "zod";

const API_URL =
  process.env.PHONE_PREFIXES_SOURCE_URL ??
  "https://api.saasmint.net/api/v1/phone-prefixes/";

const OUTPUT_PATH = resolve(
  import.meta.dirname,
  "../src/domain/data/phonePrefixes.ts",
);

const PhonePrefixSchema = z.object({
  prefix: z.string(),
  label: z.string(),
});

const ResponseSchema = z.array(PhonePrefixSchema);

async function main() {
  console.log(`Fetching ${API_URL}…`);
  const res = await fetch(API_URL);
  if (!res.ok) {
    throw new Error(`Fetch failed: ${res.status} ${res.statusText}`);
  }

  const raw = await res.json();
  const prefixes = ResponseSchema.parse(raw);

  const body = `// AUTO-GENERATED by scripts/sync-phone-prefixes.ts. Do not edit by hand.
// Run \`pnpm sync:phone-prefixes\` to refresh from the backend, then commit.
import type { PhonePrefix } from "@/domain/models/PhonePrefix";

export const PHONE_PREFIXES: readonly PhonePrefix[] = ${JSON.stringify(
    prefixes,
    null,
    2,
  )};
`;

  writeFileSync(OUTPUT_PATH, body);
  console.log(`Wrote ${prefixes.length} prefixes → ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
